//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
using GalaSoft.MvvmLight;

namespace TEST1_.Data
{
    using System;
    using System.Collections.Generic;

    public interface IElement: INotifyPropertyChanged
    {
        int ID { get; set; }
        string Name { get; set; }
        Nullable<int> Age { get; set; }
    }
    public partial class Dog: 
       ObservableObject, IElement
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Age { get; set; }
    }
}
